title: neoRL.net
logo: img/experiment4.png
  # img/neoRLnet.png
  # img/experiment4.png
theme: jekyll-theme-minimal
name: Per R. L.
description: R&D Services for innovative projects on digitalization; technology development; project management and soft funding.
markdown: kramdown
highlighter: rouge
