title: Autonomous navigation in the (animal and the) machine
logo: img/meg.jpeg
theme: jekyll-theme-minimal
name: Per R. L.
description: Information about the neoRL project.
markdown: kramdown
highlighter: rouge
