title: neoRL.net
logo: img/experiment4.png
  # img/neoRLnet.png
  # img/experiment4.png
theme: jekyll-theme-minimal
name: Per R. L.
description: R&D Services for innovative projects on digitalization; project- and technology development; soft funding and project management.
markdown: kramdown
highlighter: rouge
