title: neoRL.net R&D Services
logo: img/experiment4.png
theme: jekyll-theme-minimal
name: Per R. L.
description: R&D Services for autonomy and digitalization, and info on the *neoRL* framework for autonomous navigation.
markdown: kramdown
highlighter: rouge
