logo: img/neoRLnet.png
  # img/neoRLnet.png
  # img/experiment4.png
theme: jekyll-theme-minimal
name: Per R. L.
description: R&D Services help innovative projects with digitalization; project- and technology development; and, soft funding.
markdown: kramdown
highlighter: rouge
