title: Autonomous navigation in the (animal and the) machine
logo: img/experiment4.png
theme: jekyll-theme-minimal
name: Per R. L.
description: Information about neoRL.net R&D services, and the [neoRL] framework for autonomous navigation.
markdown: kramdown
highlighter: rouge
