title: Digitalization R&D Services
logo: img/neoRLnet.png
theme: jekyll-theme-minimal
name: Per R. L.
description: R&D Services for autonomy and digitalization, and info on the __neoRL__ framework for autonomous navigation.
markdown: kramdown
highlighter: rouge
